### ISSUE TITLE
cupti main.go doesnt work

### ISSUE THREAD

**Issue by yoonlee95** [rai-project/go-cupti#1]
This is what I get when I run cupti/main.go
this is my output when I run the code

As you can see it can get the version of cupti so I do not thing there is a problem with the binding
```
read config /home/john/.carml_config.yml
DEBU[0000] loading cupti library                         pkg=go-cupti lib=/usr/local/cuda/extras/CUPTI/lib64/libcupti.so.8.0
[/home/john/.carml_config.yml]Finished setting configuration...
DEBU[0000] running cupti                                 version="CUPTI Version = 9" bin=cupti
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/rai-project/go-cupti.(*CUPTI).cuptiSubscribe.func1(0xc420162198, 0xb18e60, 0xc42019d960, 0x68)
        /home/john/.gvm/pkgsets/go1.9/global/src/github.com/rai-project/go-cupti/subscribe.go:33 +0xcf
github.com/rai-project/go-cupti.(*CUPTI).cuptiSubscribe(0xc42019d960, 0x0, 0x135e5e0)
        /home/john/.gvm/pkgsets/go1.9/global/src/github.com/rai-project/go-cupti/subscribe.go:34 +0x5a
github.com/rai-project/go-cupti.(*CUPTI).Subscribe(0xc42019d960, 0xc42019d960, 0x1)
        /home/john/.gvm/pkgsets/go1.9/global/src/github.com/rai-project/go-cupti/cupti_linux.go:101 +0x35
github.com/rai-project/go-cupti.New(0xc4201b3ee8, 0x1, 0x1, 0xd050c5, 0xa, 0x0)
        /home/john/.gvm/pkgsets/go1.9/global/src/github.com/rai-project/go-cupti/cupti_linux.go:47 +0xae
main.main.func1(0x1327660, 0xc420014110)
        /home/john/.gvm/pkgsets/go1.9/global/src/github.com/rai-project/go-cupti/cupti/main.go:71 +0x11b
main.main()
        /home/john/.gvm/pkgsets/go1.9/global/src/github.com/rai-project/go-cupti/cupti/main.go:88 +0x14e
exit status 2
```

This is my driver/gpu info
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:0B:00.0  On |                  N/A |
| 24%   45C    P8     8W / 120W |   2080MiB /  6069MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+

```

**Comment by abduld** [comment]
put `export GODEBUG=cgocheck=0` in your `.bashrc` or `.zshrc`

See https://rai-project.github.io/carml/#/installation?id=cgo-pointer-errors
